# Site settings
title: Kevin Bigelow Design
email: kbigelow.design@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  From wireframes to code, I design and build interfaces.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kevinbigelow.design"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
