# Site settings
title: Kevin Bigelow Design
myname: Kevin Bigelow
jobtitle: UI Designer & Developer
email: kbigelow.design@gmail.com
description: From wireframes to code, I design and build interfaces.
baseurl: ""
url: "http://www.kevinbigelow.design"
twitter_username: jekyllrb
github_username:  KevinBigelow
permalink: :title

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
